### ISSUE TITLE
Practice Nested Repeaters

### ISSUE THREAD

**Issue by dgilleland** [dgilleland/2019-Sep-In-Class#3]
Create a page that shows our suppliers and the products they offer. I will need to see information in the following "structure"

- **Supplier:**
  - Company Name
  - Contact Name
  - Phone Number
  - **Product Summary:**
    - Product Name
    - Category Name
    - Unit Price
    - Quantity/Unit

## Tasks

- [ ] Create LINQ query in LinqPad
- [ ] Create classes for the *Read Model*
- [ ] Copy/Adapt LinqPad query to BLL method
- [ ] Create page with nested repeater
